services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_URL=http://imontero.ddns.net:8000  #http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - hypertube-network
    restart: unless-stopped
