services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL}
    environment:
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - hypertube-network
    restart: unless-stopped

networks:
  hypertube-network:
    name: hypertube-network
    driver: bridge

    